.TH "SYSTEMSTATS" "1" "15 Nov 2022" "0.3" "SYSTEMSTATS man page"

.SH "NAME"
systemstats \- retrieves information about the host system 

.SH "SYNOPSIS"
.HP \w'\fRsystemStats\fR\ 'u
\fRsystemStats\fR [\-F\ \fIcpu usage\fR] [\-i \fIIP address\fR] [\-t \fITemperature\fR] [\-c\ \fICPU cores\fR] [\-V\ \fIVoltage\fR] [\-m\ \fIArm memory\fR] [\-M\ \fIGPU memory\fR] [\-f\ \fIFree memory\fR] [\-d\ \fIDisk Space\fR] [\-h\ \fIHelp\fR]
.br

.SH "DESCRIPTION"
.PP
\fB\-F\fR
.RS
  show current CPU Usage FREE=##.##\% Used=##.##\%
.RE
.PP
\fB\-i\fR
.RS
  show host IPv4 address
.RE
.PP
\fB\-t\fR
.RS
  get min, max and average temperature of system from temperature -t command
.RE
.PP
\fB\-c\fR
.RS
  Show current CPU core count
.RE
.PP
\fB\-V\fR
.RS
  Show current system voltage
.RE
.PP
\fB\-m\fR
.RS
  Show current system memory
.RE
.PP
\fB\-M\fR
.RS
  Show current system GPU memory
.RE
.PP
\fB\-f\fR
.RS
  Show current systems available free memory
.RE
.PP
\fB\-d\fR
.RS
  Show current systems available and used disk space
.RE
.PP
\fB\-h\fR
.RS
  Show help information for the command
.RE

.SH "NOTES"
This script will be developed over time to display more information using different options

.SH "BUGS"
Any bugs(features) please use the suggestion bin ... >/dev/null

.SH "AUTHORS"
Charles Stratton\-Brown <charlesstrattonbrown@gmail.com>
