#! /usr/bin/env bash


USAGE(){
	echo -e $1
	echo -e "\nUseage: temperature [-m minimum temperature] [-M maximum temperature] [-a average temperature] [-h median temperature]"

}

if [[  ( $# -gt 1) || ( ${#1} -gt 5 )  ]];then
	USAGE "To many arguements"
	exit 1
elif [[ ( $1 == '--help' ) || ( $1 == '-h' ) ]];then
	USAGE "Help"
	exit 0
fi
if [ $# -lt 1 ];then
	USAGE "Not enough arguments"
	exit 1
fi

TEMPERATURESTATS()
{
	DIVIDE=1000
	TEMPS=$(cat /sys/class/thermal/thermal_zone*/temp | sort -n)

############## STATISTICS #################

MIN=${TEMPS[0]}
MAX=0

for T in ${TEMPS[@]}
do
	if [[ ${T} > ${DIVIDE} ]]; then
		T=$( echo 'scale=2;'"${T}" | bc -l )
		SUM=$(( ${SUM} + ${T} ))
		SIZE=$(( ${SIZE} + 1 ))
		

		if [[ ${MAX} < ${T} ]]; then
			MAX=${T}
		fi

		if [[ ( ${MIN} > ${T} ) && ( ${T} > 0 ) ]]; then
			MIN=${T}
		fi
		fi
	done

	AVGTEMP=$( awk " BEGIN { printf ( ${SUM} / ${SIZE} / ${DIVIDE} ) } " | awk '{ printf "%2.2f\n", $0 } ')

# Calculate Median
if [[ $((${SIZE} % 2 )) == 0 ]]; then
	MIDDLE=$(( ${SIZE} / 2 ))
	else
	MIDDLE=$(( ( ${SIZE} + 1 ) / 2 ))
fi

TMP=$( echo ${TEMPS[@]} | awk -v POS="${MIDDLE}" '{ printf $POS } ' )

MEDIAN=$( awk "BEGIN { printf ( ${TMP} / ${DIVIDE} ) } " | awk '{ printf "%2.2f\n",$0 }' )

MIN=$( awk " BEGIN { printf ( ${MIN} / ${DIVIDE} ) } " | awk ' { printf "%2.2f\n",$0 } ' )
MAX=$( awk " BEGIN { printf ( ${MAX} / ${DIVIDE} ) } " | awk ' { printf "%2.2f\n",$0 } ' )


}




while getopts "mMant" OPTION
do
case ${OPTION}
in

m)TEMPERATURESTATS
   echo "Minimum temperature: ${MIN}";;
M)TEMPERATURESTATS
    echo "Maximum temperature: ${MAX}";;
a)TEMPERATURESTATS
   echo "Average temperature: ${AVGTEMP}";;
n)TEMPERATURESTATS
   echo "Median temperature: ${MEDIAN}";;
t)TEMPERATURESTATS
   echo "Min: ${MIN} Max: ${MAX} Avg: ${AVGTEMP} Med: ${MEDIAN}";;
*) USAGE "\n${*} argument was not recognized";;
esac
done
